### ISSUE TITLE
autograph-edge.prod.mozaws.net has failed the SecOps Baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla-services/autograph-edge#36]
Site https://autograph-edge.prod.mozaws.net has failed the SecOps Baseline scan.

The failing tests are:

 Strict-Transport-Security Header Not Set [10035] x 3 
 * https://autograph-edge.prod.mozaws.net/ (503 Service Unavailable: Back-end server is at capacity)
 * https://autograph-edge.prod.mozaws.net/robots.txt (503 Service Unavailable: Back-end server is at capacity)
 * https://autograph-edge.prod.mozaws.net/sitemap.xml (503 Service Unavailable: Back-end server is at capacity)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=autograph-edge.prod.mozaws.net) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by psiinon** [comment]
Closing manually as this site is no longer tracked.
